version: "3"
services:
  test:
    image: openjdk:21-jdk
    container_name: test
    environment:
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "8987:8080"
    command: java -jar /home/ROOT.jar
    volumes:
      - ./target:/home
      - ./logs:/logs
